### ISSUE TITLE
To be able to add input option when setting hitlist command 

### ISSUE THREAD

**Issue by codad5** [hitlist-cli/cli#1]
Can there be an option to be able to accept input  while setting hitlist command
Something like 
> -/hit $ hit create testhit

> ? Hits (commands separated by commas) : git add { * }, git commit -m { * }, git push 

> ...

so that one run the hit will be like

> -/hit $ hit r  -p codad5 init-push --f '.' 'testing commit' 

The `--f` command find in all the various strings after into the `{*}` in the same order as the string is given

**Comment by aosasona** [comment]
A git commit shortcut already exists but I will consider this extra “formatting” but for now, you could take a look at this https://github.com/hitlist-cli/cli#push-to-a-set-git-repository
